//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_ly_don_hang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuffetTicketMenuItem
    {
        public int BuffetTicketMenuItemID { get; set; }
        public int BuffetTicketID { get; set; }
        public int MenuItemID { get; set; }
    
        public virtual BuffetTicket BuffetTicket { get; set; }
        public virtual MenuItem MenuItem { get; set; }
    }
}
