//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_ly_don_hang.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int EmployeeID { get; set; }
        public int OrderID { get; set; }
        public int OrderTaxID { get; set; }
        public int ShiftID { get; set; }
        public int TotalPriceBuffetTicket { get; set; }
        public int TotalDiscountPrice { get; set; }
        public int TotalValueTax { get; set; }
        public int TotalAmount { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public int Status { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual OrderTax OrderTax { get; set; }
    }
}
