//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quan_ly_don_hang.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyDonHang : DbContext
    {
        public QuanLyDonHang()
            : base("name=QuanLyDonHang")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuffetTicket> BuffetTickets { get; set; }
        public virtual DbSet<BuffetTicketMenuItem> BuffetTicketMenuItems { get; set; }
        public virtual DbSet<BuffetTicketTimeSlot> BuffetTicketTimeSlots { get; set; }
        public virtual DbSet<CategoryFood> CategoryFoods { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<MenuItem> MenuItems { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<ServingTable> ServingTables { get; set; }
        public virtual DbSet<Shift> Shifts { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<OrderTax> OrderTaxes { get; set; }
    }
}
